trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Install and Build Dependencies'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'  # Ensure the correct version of Node.js is used
      displayName: 'Install Node.js'

    - task: Npm@1
      inputs:
        command: 'install'
      displayName: 'Install dependencies'

    - script: |
        chmod +x node_modules/.bin/*  # Ensure permissions for Mocha
        npm test                      # Run tests
      displayName: 'Run Tests'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    steps:
    - script: |
        npm test
      displayName: 'Run Tests'
