# azure-pipelines.yml

trigger:
- main 

pool:
  vmImage: 'ubuntu-latest'  

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Install Dependencies'
    steps:
    # Step 1: Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x' 
      displayName: 'Install Node.js'

    # Step 2: Install dependencies (including Mocha)
    - task: Npm@1
      inputs:
        command: 'install'
      displayName: 'Install dependencies'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build  
  jobs:
  - job: TestJob
    displayName: 'Run Tests'
    steps:
    # Step 3: Ensure permissions for Mocha and run tests
    - script: |
        chmod +x node_modules/.bin/*  
        npx mocha tests/*.js   
      displayName: 'Run Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-results.xml'  # Adjust the file path based on your Mocha reporter output
        testRunTitle: 'Mocha Test Results'
      displayName: 'Publish Test Results'
